### PR TITLE
Change

### PR DESCRIPTION
**Pull request by nongojames1**
Lets change the doctor header.

### CODE REVIEW

**Comment by DorKoang** [comment]
Why are u changing doctor header? can you tell us the reason

**Comment by DorKoang** [comment]
Why are u changing doctor header? can you tell us the reason

**Comment by isharakasereka** [comment]
good

**Comment by Mugerwa-Joseph** [comment]
> Can't we view our changes while viewing the system interface working on line instead of only the codes only. Your kind respond will aid our learning!

Thanks Hackim for that concern, however, i had left it out as task for someone to host the project for us on a free domain and we see how it runs, unfortunately, vo one took up the challenge to host the project for us.

I will be working on hosting it and i will be calling upon you to help in the further development of the project.

Thanks.

**Pull request closed without merging**
