### PR TITLE
my contribution to the system is the backup system that is able to cr…

### PR DESCRIPTION
**Pull request by nongojames1**
…eate a database backup for the hospital system.

### CODE REVIEW

**Comment by david-lee-chan** [comment]
can you change the project from MySQL to MYSQLI?
I am GETTING SO MANY ERRORS.

**Comment by clariceabia** [comment]
that is a good contribution
keep it up

**Comment by david-lee-chan** [comment]
where is the backup database saved? i tried to check your php script but i do not know if the database can be saved by default

**Comment by Mugerwa-Joseph** [comment]
> can you change the project from MySQL to MYSQLI?
> I am GETTING SO MANY ERRORS.

True, you can convert it from MYSQL to MYSQLi if your server no longer supports MYSQL.

Give it a go....

**Pull request closed without merging**
