### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Gimu17**
I added a remember me button below the login on the index page to prevent frequent users of the system from typing they emails and passwords over and over again, and also added in some background color on the login interface table on index.

### CODE REVIEW

**Comment by isharakasereka** [comment]
it is a nice hospital management system

**Comment by DorKoang** [comment]
Thanks Hakim James

**Comment by mutamirimoyo** [comment]
i can feel it

**Comment by feyofficial5** [comment]
This is great

**Comment by olivierbyesi** [comment]
i love it

**Comment by layla123** [comment]
wonderful ,like it

**Comment by xaramazina2** [comment]
wondeful project....

**Comment by diemesaanane** [comment]
very good

**Comment by Mugerwa-Joseph** [comment]
Thanks James for that input.

Lets go further to update the project further.

**Pull request closed without merging**
